version: "3"

services:
  bookshop:
    image: bookshop
    build: .
    volumes:
      - ./:/go/src/github.com/damianopetrungaro/golang-bookshop/
    ports:
      - 80:80
    environment:
      - ENV_NAME=development
    entrypoint: ["task", "refresh", "-w"]