version: "3"

services:
  bookshop:
    image: bookshop
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./:/go/src/github.com/damianopetrungaro/golang-bookshop/
    ports:
      - 80:80