version: "3"

services:
  bookshop:
    image: bookshop
    build: .
    ports:
      - 80:80
    networks:
      - api
      - persistence
    depends_on:
      - postgresql
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgresql/:/var/lib/postgresql/data
    networks:
      - persistence
networks:
  api:
    driver: "bridge"
  persistence:
    driver: "bridge"