build:
  desc: Build the go binary.
  cmds:
    - go build -o /go/bin/bookshop .

deps:
  desc: Install the dependecies.
  cmds:
    - glide install

refresh:
  desc: Refresh the running program.
  cmds:
    - pkill bookshop || true
    - go build -o /go/bin/bookshop . && /go/bin/bookshop &
  sources:
    - ./**/*.*